const illustrationImage = document.getElementById('illustration-signup-img')
const signupForm = document.querySelector('.signup-form')
const emailInput = document.getElementById('email')
const emailValidMsg = document.getElementById('emailValid')
const successEmail = document.getElementById('successEmail')

if(illustrationImage){
    illustrationImage.src = `/assets/images/${window.innerWidth > 600 ? 'illustration-sign-up-desktop.svg': 'illustration-sign-up-mobile.svg'}`
}

if(successEmail && sessionStorage.getItem('email')){
    successEmail.textContent = sessionStorage.getItem('email')
}

window.addEventListener('resize', ()=>{
    if(illustrationImage){
        illustrationImage.src = `/assets/images/${window.innerWidth > 600 ? 'illustration-sign-up-desktop.svg': 'illustration-sign-up-mobile.svg'}`
    }
})

signupForm?.addEventListener('submit', (evt)=>{
    if(!isEmail(emailInput.value)){
        evt.preventDefault()
        emailInput.style.border = '2px solid red'
        emailInput.style.color = 'red'
        emailValidMsg.style.visibility = 'visible'
        return
    }
    sessionStorage.setItem('email', emailInput.value)
})

emailInput?.addEventListener('input', ()=>{
    emailInput.style.border = ''
    emailInput.style.color = ''
    emailValidMsg.style.visibility = 'hidden'
    console.log('hi')
})

// generated by ai 🙃
function isEmail(email) {
    return  /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email).toLowerCase())
}
  